name: codacy-coverage-reporter

on: ["push"]

jobs:
  calculate-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest coverage
        pip install -r requirements.txt
    - name: Calculate coverage
      run: |
        coverage run -m pytest
        coverage report
        coverage xml -o cobertura.xml
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@v1.3.0
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: cobertura.xml
      
